name: CI to Docker Hub

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for tags vX.X.X
  push:
    tags:
      - "v*.*.*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow call reusable workflow docker-build
  build:
    uses: rubensa/docker-devcontainers-cli/.github/workflows/docker-build.yml@master
    with:
      DOCKER_REPOSITORY_NAME: rubensa
      DOCKER_IMAGE_NAME: devcontainers-cli
      DOCKER_IMAGE_TAG: latest
      # see: https://github.com/devcontainers/features/pull/833#issuecomment-2346085769
      DOCKER_IMAGE_PLATFORMS: linux/amd64
    secrets: inherit
